language: node_js
before_install:
  - "sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test"
  - "sudo apt-get update"
  - "sudo apt-get install build-essential g++-4.8 libcairo2-dev libpango1.0-dev --force-yes"
  - "export CXX='g++-4.8'"
